### ISSUE TITLE
运行异常

### ISSUE THREAD

**Issue by vividkings** [xresloader/xresloader#10]
[ERROR] xresloader - org.apache.poi.ooxml.POIXMLException: error: 已经为元素 "v:fill" 指定绑定到名称空间 "urn:schemas-microsoft-com:office:office" 的属性 "relid"。
[ERROR] xresloader - 	org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:68)
[ERROR] xresloader - 	org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:660)
[ERROR] xresloader - 	org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:677)
[ERROR] xresloader - 	org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:165)
[ERROR] xresloader - 	org.apache.poi.xssf.usermodel.XSSFWorkbook.(XSSFWorkbook.java:278)
[ERROR] xresloader - 	org.apache.poi.xssf.usermodel.XSSFWorkbook.(XSSFWorkbook.java:299)
[ERROR] xresloader - 	org.xresloader.core.engine.ExcelEngine.openWorkbook(ExcelEngine.java:219)
[ERROR] xresloader - 	org.xresloader.core.engine.ExcelEngine.openUserModuleSheet(ExcelEngine.java:241)
[ERROR] xresloader - 	org.xresloader.core.data.src.DataSrcExcel.init_sheet(DataSrcExcel.java:211)
[ERROR] xresloader - 	org.xresloader.core.data.src.DataSrcExcel.init(DataSrcExcel.java:51)
[ERROR] xresloader - 	org.xresloader.core.main.build_group(main.java:227)
[ERROR] xresloader - 	org.xresloader.core.main.main(main.java:376)
[ERROR] xresloader - Panic!, it's probably a BUG, please report to https://github.com/xresloader/xresloader/issues, current version: 2.11.0

**Comment by owent** [comment]
可否提供一下示例的配置？

**Comment by owent** [comment]
感谢提供数据，经初步排查是POI把一处Drawing数据命名判定有问题。临时的解决方法是使用 `--disable-excel-formular` 选项关闭POI的索引引擎，而改用xresloader内置的索引器。
等后面更新了POI再观察看看

**Comment by owent** [comment]
默认已经改为使用内置索引器
