### ISSUE TITLE
请问kind.pb是生成的还是手写的？

### ISSUE THREAD

**Issue by goofansu** [xresloader/xresloader#2]
这个工具会生成proto文件吗？因为我的后端是Erlang，前端是Lua，所以想生成proto，然后用各自的官方工具，生成pb文件。

看到这里有`kind.pb`，不知道是哪里来的，不像是手写的。

谢谢。

**Comment by owent** [comment]
@goofansu  kind.pb是由 kind.proto，dependency.proto和dep_level2.proto生成的
用protobuf自带的protoc生成就可以了

**Comment by goofansu** [comment]
@owt5008137 就是说这个工具是根据proto和策划的配置文件，来生成用于打包的bin文件之类的是吗？我本来以为是生成proto文件的

**Comment by owent** [comment]
@goofansu 是的，已更新sample里的README.md了。是用来把Excel内的数据按照程序定制的结构生成代码和相应的bin。用于程序中高性能且结构化地读取

**Comment by goofansu** [comment]
明白了，Erlang如何读取我倒不太清楚，我身边用lua的同事是转成bin文件读的。

谢谢了

**Comment by owent** [comment]
@goofansu erlang和lua都有相关的库可以直接读取protobuf数据的。应该是只编写proto文件，然后分别由lua和erlang加载（或者生成相应的源码）。因为protobuf官方并没有erlang支持，所以不知道erlang那个第三方工具是否是和protobuf官方的操作方式一样。protobuf官方的操作方式是会生成各种语言的代码的。

我们这里是后端和前端都是C++ + Lua。C++使用protobuf原生的生成的代码加载的。Lua的常量是导出成Lua代码加载的，配置数据是使用PBC加载的。还有个GM工具是导出成javascript使用。

**Comment by goofansu** [comment]
@owt5008137 谢谢解答。

Erlang有第三方库根据proto生成pb，但是你这个工具是再根据pb和策划的配置生成bin，我不知道生成的bin如何调用。lua和C#我知道是有库可以读取结构化的bin文件的。

**Comment by owent** [comment]
使用https://github.com/xresloader/xresloader/blob/master/header/pb_header.proto 里的 xresloader_datablocks 结构parse转出的bin文件的二进制buffer。然后每个xresloader_datablocks.data_block使用配置里填的那个message进行parse即可。
伪代码就是：

```
FILE_DATA = open('xxx.bin', 'rb').read_all()
ALL_DATA = com.owent.xresloader.pb.xresloader_datablocks.parse(FILE_DATA);
for LINE_BUFFER in ALL_DATA.data_block do
     EXCEL_LINE = [自定义协议].parse(LINE_BUFFER)
     ... 
     EXCEL_LINE 就是每一行Excel数据转出的对应的[自定义协议]的对象
     比如建立索引 CFG_SET[EXCEL_LINE.id] = EXCEL_LINE
end
```

https://github.com/owent-utils/lua/blob/master/src/data/pbc_config_manager.lua
和
https://github.com/xresloader/xresloader/blob/master/loader-binding/cxx/libresloader.h
里的代码都是除了读取以外还会建立索引的，因为一般情况下使用配置的话都会需要Key-Value的索引。

**Comment by goofansu** [comment]
@owt5008137 好的，我研究下，多谢
