### ISSUE TITLE
.pb文件使用

### ISSUE THREAD

**Issue by 007havegone** [xresloader/xresloader#28]
看文档和配置文件，多个 proto文件最终只需要导出一个 pb文件？如果目前导出多个pb文件，批量处理配置文件语法上支持填写多个么，还是只能支持1个。

**Comment by owent** [comment]
目前只支持一个，后续有计划增加多个pb文件支持。这个涉及pb文件Merge，比较麻烦可能会比较晚再抽时间实现。
