### ISSUE TITLE
DataTable功能支持情况

### ISSUE THREAD

**Issue by 007havegone** [xresloader/xresloader#29]
一个Excel通过一个主键+列名引用另一个表格的某一行某一列数据可以么？比如在表格A使用表格B的主键和列明，表格B配置了资源，能否导入时替换为表格B中相应的数据，而不用在程序内查询两层。

**Comment by owent** [comment]
这个功能在计划中，会增加一种更通用的rule机制以便多个表复用规则。
目前可以先用Excel自带的数据验证功能。

**Comment by owent** [comment]
抱歉之前理解错了，这个是不是可以通过Excel公式功能完成？如果是需要两个表key相同，字段合并的话，目前并不在计划中。
计划中会增加的功能是两个sheet互相验证key字段存在性检测。
