### ISSUE TITLE
Bug——引用枚举类型，指定uint32但实际代码是int32

### ISSUE THREAD

**Issue by 007havegone** [xresloader/xresloader#32]
我定义了一个enum枚举变量，在另一个message定义了一个uint32，同时使用org.xresloader.verfier 引用这个enum。生产的UE 中这个成员的类型变成了 int32。我看了你给的sample中 role_cfg的cost_type也是一样的情况。

**Comment by owent** [comment]
UE蓝图不支持unsigned整数。所以所有的这类类型全部转成有符号类型的。

**Comment by 007havegone** [comment]
好的，谢谢解答。
