### ISSUE TITLE
pb文件的使用和bin导出的修改校验

### ISSUE THREAD

**Issue by OnlyLiu** [xresloader/xresloader#33]
1、pb文件使用
将proto转成二进制pb是为了运行时速度吗？是否可以根据描述文件的后缀（.pb或者proto）同时支持？不想转表之前还需要多一步操作。pb文件还需要提交。

2、bin导出的修改校验
如果导出的bin文件md5一样，内容没有修改，是否可以不进行导出？

**Comment by owent** [comment]
1. java不支持proto转pb。只有C++编译出来的protoc才支持。因为生成的代码大多语言protoc和protobuf必须保持一致，所以大部分工程会自己管理protoc。故而没有在xresloader冗余打包各个平台的protoc。三个主要平台的protoc加起来要有将近20MB了。
2. 现在是先导出再生成hash值的。底层处理是流式接口，再全部转完之前不知道hash值是啥。这里想不进行导出的目的是啥呢？如果是想没变化不刷新时间戳的话可用类似 copy_if_different 的方式代替？

**Comment by OnlyLiu** [comment]
一键转表之后，只想提交有修改的转表。不用自己去甄别。

**Comment by OnlyLiu** [comment]
> 1. java不支持proto转pb。只有C++编译出来的protoc才支持。因为生成的代码大多语言protoc和protobuf必须保持一致，所以大部分工程会自己管理protoc。故而没有在xresloader冗余打包各个平台的protoc。三个主要平台的protoc加起来要有将近20MB了。
> 2. 现在是先导出再生成hash值的。底层处理是流式接口，再全部转完之前不知道hash值是啥。这里想不进行导出的目的是啥呢？如果是想没变化不刷新时间戳的话可用类似 copy_if_different 的方式代替？

一键转表之后，只想提交有修改的转表。不用自己去甄别。

**Comment by OnlyLiu** [comment]
1、我想表达的是，是否可以不需要下面的pb的二进制文件，利用proto描述文件就可以直接转表了？

![image](https://github.com/xresloader/xresloader/assets/7315469/852aeb8a-0b41-4556-90e1-1fa01305a64b)

比如不需要这里的 sample.pb 

convlist.xml里面的ProtoName其实是有配置excel对应的proto，我理解可以直接反射转表就可。

2、一键转表之后，只想关注有修改的转表。

是否先加载下旧的文件hash值，然后转完成的时候对比一下，然后决定是否需要覆盖？

3、一般客户端和服务器的配置会有不一样，category 能否直接按照树形结构配置 或者 可以根据tag筛选也行的？
例如：
![image](https://github.com/xresloader/xresloader/assets/7315469/1811e865-5fff-467e-a4b8-9346c71a7521)

**Comment by owent** [comment]
> 1、我想表达的是，是否可以不需要下面的pb的二进制文件，利用proto描述文件就可以直接转表了？
> 
> ![image](https://user-images.githubusercontent.com/7315469/246338311-852aeb8a-0b41-4556-90e1-1fa01305a64b.png)
> 
> 比如不需要这里的 sample.pb
> 
> convlist.xml里面的ProtoName其实是有配置excel对应的proto，我理解可以直接反射转表就可。
> 
> 2、一键转表之后，只想关注有修改的转表。
> 
> 是否先加载下旧的文件hash值，然后转完成的时候对比一下，然后决定是否需要覆盖？

1. 并不可以，只有C++有解析proto文件的能力。为了跨平台，这是个java写的工具。
2. 这个大多数VCS都有，所以不倾向于重复造这个轮子
3. tree只是为了GUI工具显示。要区分服务器和客户端表可以配置不同的输出矩阵，选中不同的tag或者class
