### ISSUE TITLE
关于代码生成问题

### ISSUE THREAD

**Issue by pathofe** [xresloader/xresloader#37]
作者你好，求指导三个问题（在UE项目中使用表格问题）。   
1. 使用xres-code-generator-main工程直接生成PbCpp代码时候， 我在.Proto文件里面定义的ue_type_name之类的字段(类似  string   XX  = 1  [ (org.xresloader.ue.ue_type_name) = "class XXXX"])。  看了下转成出来res.pb.h里面的定义，似乎只会被生成为普通的String结构。     这里是需要我手动把String 转成成虚幻的  FSoftObjectPath 类型来使用吗？  不知道这块理解对不对。
2. GUI工具生成UE文件 可以用 xres-code-generator-main来生成出来吗？    当在GUI里面选择UE-CSV结构时候，会生成继承FTableRowBase结构的.h文件。  但是看了xres-code-generator-main介绍似乎只能生成UE(UnrealEngine) Blueprint这种类型，这种他直接继承的UObject，似乎没上面FTableRowBase使用方便。 
3. 直接用GUI工程生成的代码文件 似乎没办法生成枚举.   导致枚举只能被转为int。  这个是UE 本身的限制吗？

**Comment by owent** [comment]
1. [xres-code-generator][1] 并不使用 `org.xresloader.*` 的插件。它有自己的插件 ( `https://github.com/xresloader/xres-code-generator/blob/main/pb_extension/xrescode_extensions_v3.proto` ) 。它和 xresloader 自带的转表是独立的，最近也增加了对UE的支持 （ https://github.com/xresloader/xres-code-generator/blob/main/README.md#for-ueunrealengine-blueprint-support ），但是目前不支持指定类型。
2. 目前不支持。[xres-code-generator][1] 本身是支持原生C++的读表代码生成的，新增的UE支持只是包了一层导出蓝图接口给UE使用，并没有直接存储数据。后续可以加自定义类型的支持，但是目前还不支持。
3. 是的，UE蓝图只能uint8，但是pb是int32。所以在 [xres-code-generator][1] 新加的模板中，对于uint8以下的enum，导出蓝图enum，其他情况下导出了普通的enum。具体是 ( https://github.com/xresloader/xres-code-generator/blob/main/template/UEExcelEnum.h.mako 和 https://github.com/xresloader/xres-code-generator/blob/main/template/UEExcelLoader.h.mako ) 这两个模板。


[1]: https://github.com/xresloader/xres-code-generator

**Comment by pathofe** [comment]
> * 是的，UE蓝图只能uint8，但是pb是int32。所以在 [xres-code-generator](https://github.com/xresloader/xres-code-generator) 新加的模板中，对于uint8以下的enum，导出蓝图enum，其他情况下导出了普通的enum。具体是 ( https://github.com/xresloader/xres-code-generator/blob/main/template/UEExcelEnum.h.mako 和 https://github.com/xresloader/xres-code-generator/blob/main/template/UEExcelLoader.h.mako ) 这两个模板。
这个支持还是针对是的xres-code-generator。      GUI工具导出UE-CSV生成的代码有没有办法支持下枚举？

**Comment by owent** [comment]
> > * 是的，UE蓝图只能uint8，但是pb是int32。所以在 [xres-code-generator](https://github.com/xresloader/xres-code-generator) 新加的模板中，对于uint8以下的enum，导出蓝图enum，其他情况下导出了普通的enum。具体是 ( https://github.com/xresloader/xres-code-generator/blob/main/template/UEExcelEnum.h.mako 和 https://github.com/xresloader/xres-code-generator/blob/main/template/UEExcelLoader.h.mako ) 这两个模板。
> >   这个支持还是针对是的xres-code-generator。      GUI工具导出UE-CSV生成的代码有没有办法支持下枚举？

也是一样的原因，xresloader现在可以导出枚举为字符串到int的 key-value 。但是为了兼容性底层只能用int32哈
