### ISSUE TITLE
转表错误

### ISSUE THREAD

**Issue by vividkings** [xresloader/xresloader#5]
[ERROR] xresloader - java.lang.IllegalArgumentException: Wrong object type used with protocol message reflection.
[ERROR] xresloader - 	com.google.protobuf.FieldSet.verifyType(FieldSet.java:402)
[ERROR] xresloader - 	com.google.protobuf.FieldSet.addRepeatedField(FieldSet.java:372)
[ERROR] xresloader - 	com.google.protobuf.DynamicMessage$Builder.addRepeatedField(DynamicMessage.java:589)
[ERROR] xresloader - 	org.xresloader.core.data.dst.DataDstPb.dumpValue(DataDstPb.java:1309)
[ERROR] xresloader - 	org.xresloader.core.data.dst.DataDstPb.dumpDefault(DataDstPb.java:1338)
[ERROR] xresloader - 	org.xresloader.core.data.dst.DataDstPb.dumpStandardField(DataDstPb.java:1515)
[ERROR] xresloader - 	org.xresloader.core.data.dst.DataDstPb.dumpMessage(DataDstPb.java:1398)
[ERROR] xresloader - 	org.xresloader.core.data.dst.DataDstPb.dumpStandardField(DataDstPb.java:1498)
[ERROR] xresloader - 	org.xresloader.core.data.dst.DataDstPb.dumpMessage(DataDstPb.java:1398)
[ERROR] xresloader - 	org.xresloader.core.data.dst.DataDstPb.convData(DataDstPb.java:1275)
[ERROR] xresloader - 	org.xresloader.core.data.dst.DataDstPb.build(DataDstPb.java:831)
[ERROR] xresloader - 	org.xresloader.core.main.build_group(main.java:276)
[ERROR] xresloader - 	org.xresloader.core.main.main(main.java:376)

**Comment by vividkings** [comment]
repeated int64

**Comment by vividkings** [comment]
--enable-empty-list 启动该选项时报错

**Comment by vividkings** [comment]
--enable-empty-list 启用该选项时报错

**Comment by owent** [comment]
64位整数默认值填充有点问题。已提交dev分支，下个版本修复

**Comment by owent** [comment]
https://github.com/xresloader/xresloader/releases/tag/v2.11.0-rc1 已修复
