### ISSUE TITLE
repeated --enable-empty-list 压缩空值

### ISSUE THREAD

**Issue by vividkings** [xresloader/xresloader#6]
row[0] | row[1] | row[2] | row[3]
123     |             | 456     |

能否转成[123, 0, 456] 
仅对中间的值填充，对后面的空值压缩

**Comment by owent** [comment]
这么做得使用场景是啥呢？以前保留空值是为了方便用Excel绘制地图。所以不裁剪List严格按Excel的定义长度来

**Comment by vividkings** [comment]
> 这么做得使用场景是啥呢？以前保留空值是为了方便用Excel绘制地图。所以不裁剪List严格按Excel的定义长度来

就是能不能只对末尾的空值进行裁剪。中间的空值策划懒得填，用默认值对其填充。数组还是可变长度。

**Comment by owent** [comment]
已经部分支持: https://github.com/xresloader/xresloader/releases/tag/v2.11.0-rc1

- [x] protobuf二进制
- [x] lua
- [x] msgpack
- [x] json
- [x] xml
- [x] javascript
- [x] UE-Json
- [x] UE-Csv （ https://github.com/xresloader/xresloader/releases/tag/v2.11.0-rc3 ）

**Comment by owent** [comment]
#18 已经实现全部输出模式
